# Link repository with Travis CI
# https://travis-ci.org/

# Whitelist gh-pages branch
branches:
  only:
    - master

# Set the language
language: bash

# Set the environment path to include Pandoc binaries
env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/usr/bin/:$PATH

before_install:
  # Fetch pandoc and pandoc-citeproc binaries
  - wget https://github.com/jgm/pandoc/releases/download/2.14.2/pandoc-2.14.2-1-amd64.deb && ar p pandoc-2.14.2-1-amd64.deb data.tar.gz | tar xz
  # Install TeX Live
  - sudo apt-get update -qq
  - sudo apt-get install texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-science texlive-generic-recommended
  # Install fonts
  - sudo apt-get install lmodern

# Attempt to create a PDF
script:
  - make pdf
  - make tex
  - make docx
  - make html
